# Generated by Django 4.1.4 on 2023-01-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_productbrand_url_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بنر')),
                ('image', models.ImageField(upload_to='media/banners', verbose_name='عکس بنر')),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='url بنر')),
                ('position', models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detial', 'صفحه جزییات محصولات')], max_length=200, verbose_name='محل قرار گیری بنر')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
