# Generated by Django 4.1.4 on 2023-01-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_bannermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='position',
            field=models.CharField(choices=[(' product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه جزییات محصولات'), ('about_us', 'درباره ما')], max_length=200, verbose_name='محل قرار گیری بنر'),
        ),
    ]
