# Generated by Django 4.1.4 on 2023-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='فعال/غیرفعال'),
        ),
    ]
