# Generated by Django 4.1.4 on 2023-01-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articule_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='url_title',
            field=models.CharField(max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
    ]
