# Generated by Django 4.1.4 on 2023-01-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articule_module', '0003_articlecategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articule_module.articlecategory', verbose_name='دسته بندی والد'),
        ),
    ]
