# Generated by Django 4.1.4 on 2023-01-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articule_module', '0004_alter_articlecategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='عنوان در url')),
                ('image', models.ImageField(upload_to='media/Article', verbose_name='عکس مقاله')),
                ('short_description', models.CharField(max_length=200, verbose_name='توضیحات کوتاه')),
                ('text', models.TextField(verbose_name='متن مقاله')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('select_category', models.ManyToManyField(to='articule_module.articlecategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
