# Generated by Django 4.1.4 on 2023-01-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('response', models.TextField(null=True, verbose_name='متن پاسخ تماس با ما')),
            ],
            options={
                'verbose_name': 'تماس با ما ',
                'verbose_name_plural': 'لیست تماس یا ما',
            },
        ),
    ]
