# Generated by Django 4.1.4 on 2023-01-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.CharField(max_length=200, null=True, verbose_name='توضیحات کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/user', verbose_name='عکس کاربر'),
        ),
    ]
